services:
  app:
    build:
      context: ./project
    command: >
      sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py init_admin &&
        python manage.py runserver 0.0.0.0:8000"
    
    volumes:
      - ./project:/usr/src/app
    expose:
      - 8000
    ports:
      - 80:8000
      - 8000:8000
    hostname: chathost
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./project/.env.dev

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass devtoolssecret
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local