# Generated by Django 4.0 on 2023-03-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_timestamp_message_created_at_and_more'),
        ('accounts', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='UserGroup',
        ),
        migrations.RenameModel(
            old_name='GroupProfile',
            new_name='UserGroupProfile',
        ),
    ]
