# Generated by Django 4.0 on 2023-01-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_joined'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
    ]
