# Generated by Django 4.0 on 2023-01-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_joined'),
        ('main', '0002_conversation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_to_group', to='accounts.group'),
        ),
    ]
